include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - local: 'ci/stages.yml'
  - local: 'ci/variables.yml'
  - local: 'ci/rules.yml'
  - local: 'ci/runners.yml'
  - local: 'ci/jobs.yml'

before_script:
  - mkdir -p .m2 && echo "$MAVEN_SETTINGS_XML" > ".m2/settings.xml"

workflow:
  rules:
    - if: '$SCAN'
      variables:
        PIPELINE_MODE: "scan"
    - if: '$RENOVATE'
      variables:
        PIPELINE_MODE: "renovate"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /\[build ci]/'
      variables:
        PIPELINE_MODE: "default"
        DEPENDENCY_SCANNING_DISABLED: "true"
        SAST_DISABLED: "true"
        LICENSE_MANAGEMENT_DISABLED: "true"
        SECRET_DETECTION_DISABLED: "true"