stages:
  - build
  - package
  - version

variables:
  GIT_SSL_NO_VERIFY: "true"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/maven.repository"
  IMAGE_TAG: ${CI_PIPELINE_IID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  IMAGE: ${CI_REGISTRY_IMAGE}
  BUILD_NO: ${CI_PIPELINE_IID}
  GIT_URL: ${CI_PROJECT_URL}.git
  GIT_HASH: ${CI_COMMIT_SHORT_SHA}
  GIT_BRANCH: ${CI_COMMIT_REF_SLUG}
  CONTAINER_REGISTRY: ${CI_REGISTRY_IMAGE}

maven-build:
  stage: build
  image: maven:3-jdk-8
  tags:
    - run_docker
  script:
    - mvn install -f bdd-web-app-demo/app/taxi-app/pom.xml
    - mvn install -f bdd-web-app-demo/app/testdata-sim/pom.xml
    - mvn install -f bdd-web-app-demo/test/taxi-test/pom.xml -DskipTests
    - mvn install -f bdd-web-app-demo/test/taxi-test-docker-smoketest/pom.xml -DskipTests
  artifacts:
    paths:
      - bdd-web-app-demo/app/taxi-app/target/taxi-app.jar
      - bdd-web-app-demo/app/testdata-sim/target/testdata-sim.jar
      - bdd-web-app-demo/test/taxi-test-docker-smoketest/target/smoke-tests.jar
    expire_in: 1 week

docker-build-taxi-app:
  stage: package
  image: docker:stable
  tags:
    - run_docker
  script:
    - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --pull --tag ${CI_REGISTRY_IMAGE}/app:${IMAGE_TAG} --build-arg BUILD_NO --build-arg GIT_URL --build-arg GIT_BRANCH --build-arg GIT_HASH --build-arg IMAGE_TAG --build-arg CONTAINER_REGISTRY --file demo/app/taxi-app/Dockerfile ./demo/app/taxi-app/
    - docker push ${CI_REGISTRY_IMAGE}/app:${IMAGE_TAG}

docker-build-testdata-sim:
  stage: package
  image: docker:stable
  tags:
    - run_docker
  script:
    - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --pull --tag ${CI_REGISTRY_IMAGE}/sim:${IMAGE_TAG} --build-arg BUILD_NO --build-arg GIT_URL --build-arg GIT_BRANCH --build-arg GIT_HASH --build-arg IMAGE_TAG --build-arg CONTAINER_REGISTRY --file demo/app/testdata-sim/Dockerfile  ./demo/app/testdata-sim/
    - docker push ${CI_REGISTRY_IMAGE}/sim:${IMAGE_TAG}

docker-build-smoketests:
  stage: package
  image: docker:stable
  tags:
    - run_docker
  script:
    - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --pull --tag ${CI_REGISTRY_IMAGE}/smoketests:${IMAGE_TAG} --build-arg BUILD_NO --build-arg GIT_BRANCH --build-arg GIT_HASH --build-arg IMAGE_TAG --build-arg CONTAINER_REGISTRY --file demo/test/taxi-test-docker-smoketest/Dockerfile  ./demo/test/taxi-test-docker-smoketest/
    - docker push ${CI_REGISTRY_IMAGE}/smoketests:${IMAGE_TAG}

version:
  stage: version
  image: alpine
  tags:
    - run_docker
  script:
    - echo $IMAGE_TAG
    - echo $IMAGE_TAG > version
  artifacts:
    paths:
      - version
    expire_in: 1 week
