stages:
  - build
  - package
  - version

variables:
  GIT_SSL_NO_VERIFY: "true"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/maven.repository"
  IMAGE_TAG: ${CI_PIPELINE_IID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  IMAGE: ${CI_REGISTRY_IMAGE}
  BUILD_NO: ${CI_PIPELINE_IID}
  GIT_HASH: ${CI_COMMIT_SHORT_SHA}
  GIT_BRANCH: ${CI_COMMIT_REF_SLUG}
  CONTAINER_REGISTRY: ${CI_REGISTRY_IMAGE}

maven-build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn install -f pom.xml
  artifacts:
    paths:
      - demo/app/taxi-app/target/taxi-app.jar
      - demo/app/testdata-sim/target/testdata-sim.jar
    expire_in: 1 week

docker-build-taxi-app:
  stage: package
  image: docker:stable
  script:
    - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --pull --tag ${CI_REGISTRY_IMAGE}/telekom:${IMAGE_TAG} --build-arg BUILD_NO --build-arg GIT_BRANCH --build-arg GIT_HASH --build-arg IMAGE_TAG --build-arg CONTAINER_REGISTRY --file taxi-app/Dockerfile
    - docker push ${CI_REGISTRY_IMAGE}/telekom:${IMAGE_TAG}

docker-build-testdata-sim:
  stage: package
  image: docker:stable
  script:
    - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --pull --tag ${CI_REGISTRY_IMAGE}/telekom:${IMAGE_TAG} --build-arg BUILD_NO --build-arg GIT_BRANCH --build-arg GIT_HASH --build-arg IMAGE_TAG --build-arg CONTAINER_REGISTRY --file testdata-sim/Dockerfile
    - docker push ${CI_REGISTRY_IMAGE}/telekom:${IMAGE_TAG}

version:
  stage: version
  image: alpine
  script:
    - echo $IMAGE_TAG
    - echo $IMAGE_TAG > version
  artifacts:
    paths:
      - version
    expire_in: 1 week
