version: "3"

services:
  taxi-app:
    build: bdd-web-app-demo/app/taxi-app
    environment:
      reservation-service.url: "http://testdata-sim:6000/testdata-sim/api"
    ports:
      - "5000:5000"
    links:
      - testdata-sim
    depends_on:
      - testdata-sim
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/readiness"]
      interval: 30s
      timeout: 10s
      retries: 5

  testdata-sim:
    build: bdd-web-app-demo/app/testdata-sim
    environment:
      taxi-app.url: "http://taxi-app:5000/taxi-app"
    ports:
      - "6000:6000"

  smoketest:
    build: bdd-web-app-demo/test/taxi-test-docker-smoketest
    environment:
      taxi-app.url: "http://taxi-app:5000/taxi-app"
      testdata-sim.url: "http://testdata-sim:6000/testdata-sim"
    depends_on:
      - taxi-app
      - testdata-sim
    links:
      - taxi-app
      - testdata-sim