#!/bin/bash
#
# commands triggered by CI an executed via install/deploy user
#
#set -x
   


####Main#####  

PATH="/usr/ucb:/usr/local/bin:/usr/bin:/bin:${PATH}"
USER=`whoami`
INST=`echo $USER |  sed -e"s/dep/was/"`

### Input variables

BASE=$0
DEPLOYHOST=$1
DEPLOY_VM=$2
JOBNAME=$3
INSTUSER=$4

### Defined variables

CONTEXT_BDD_WEB_APP=taxi
W_DIR=`dirname ${BASE}`
CI_DIR=/home/coinop/jenkins/workspace
TOMCAT_TARGET_DIR=BDD-WEB-APP_JENKINS
TAXI_NAME=bdd-web-app-demo-taxi
TAXI_VERSION=1.2-SNAPSHOT

if [ -f ${W_DIR}/vse_ci_execute_functions ]; then
  . ${W_DIR}/vse_ci_execute_functions
else
  echo "function file could not be localized, not loaded. ERROR!"
  exit 1
fi  

## Start
echo ""
echo "--> vse_ci_execute_BDD-WEB-APP, installation on ${INSTUSER}@${DEPLOYHOST}"

###
## stop services
kill_tomcat ${INSTUSER}

## check necessary directories
check_and_create_directory deploy_revisions/${TOMCAT_TARGET_DIR}

## deploy packages
echo "Copying ${CONTEXT_BDD_WEB_APP}.war"
scp -p ${CI_DIR}/${JOBNAME}/bdd-web-app-demo/taxi/target/${TAXI_NAME}-${TAXI_VERSION}.war  ${INSTUSER}@${DEPLOYHOST}:/home/${INSTUSER}/tomcat/deploy_revisions/${TOMCAT_TARGET_DIR}/${CONTEXT_BDD_WEB_APP}.war

echo "Cleanup enviroment"
ssh ${INSTUSER}@${DEPLOYHOST} rm -Rf /home/${INSTUSER}/tomcat/tmp/
ssh ${INSTUSER}@${DEPLOYHOST} rm -f  /home/${INSTUSER}/tomcat/log/*.*
ssh ${INSTUSER}@${DEPLOYHOST} rm -Rf /home/${INSTUSER}/tomcat/work/
ssh ${INSTUSER}@${DEPLOYHOST} rm -Rf /home/${INSTUSER}/tomcat/webapps/${CONTEXT_BDD_WEB_APP}

echo "Creating symbolic links"
ssh ${INSTUSER}@${DEPLOYHOST} ln -fs /home/${INSTUSER}/tomcat/deploy_revisions/${TOMCAT_TARGET_DIR}/${CONTEXT_BDD_WEB_APP}.war  /home/${INSTUSER}/tomcat/webapps/${CONTEXT_BDD_WEB_APP}.war

echo "Start services"
start_tomcat
